name: nusthackationwebsite
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.1.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Clarendon
      fonts:
        - asset: assets/fonts/Clarendon.otf

    - family: ClarendonBold
      fonts:
        - asset: assets/fonts/ClarendonBold.otf

    - family: MontserratEBold
      fonts:
        - asset: assets/fonts/MontserratEBold.ttf

    - family: PoppinsM
      fonts:
        - asset: assets/fonts/PoppinsM.ttf

    - family: BalooPaajiR
      fonts:
        - asset: assets/fonts/BalooPaajiR.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
